name: 'Github Action Notify Release'
description: 'Create an issue if there is a release pending'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  stale-days:
    description: 'Number of days of inactivity before a release becomes stale'
    required: false
    default: 7
  commit-messages-lines:
    description: 'Limit the number of first x lines from commit messages that will be added in the issue description. No truncation when set to 0.'
    required: false
    default: 1
runs:
  using: 'node12'
  main: 'dist/index.js'
