export const ISSUE_LABEL = 'notify-release'
export const ISSUE_TITLE = 'Release pending!'
export const STATE_OPEN = 'open'
export const STATE_CLOSED = 'closed'
export const STATE_CLOSED_NOT_PLANNED = 'not_planned'
export const ISSUES_EVENT_NAME = 'issues'
